export interface Product {
    id:Number,
    name:String,
    brandId:Number,
    brandName:String,
    code:Number,
    price:Number,
    categoryId:Number,
    categoryName:String,
    description:String,
    imagePath:String,
    active:Boolean,
    star:String,
    company:String,
    slug:Number,
}